name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd app
          npm install
          CI=false npm run build

      - name: Install Wine for packaging on Windows
        if: github.event_name == 'push'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wine64

      - name: Package
        if: github.event_name == 'push'
        run: |
          cd app
          CI=false npm run package-linux
          CI=false npm run package-mac
          CI=false npm run package-win
          cd release-builds
          zip -r App-linux-x64.zip App-linux-x64
          zip -r App-darwin-x64.zip App-darwin-x64
          zip -r App-win32-x64.zip App-win32-x64

      - name: Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/release-builds/App-linux-x64.zip
            app/release-builds/App-darwin-x64.zip
            app/release-builds/App-win32-x64.zip
