name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd app
          npm install
          CI=false npm run build

      - name: Test
        run: |
          cd app
          npm test

      - name: Install Wine for packaging on Windows
        if: github.event_name == 'push'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wine64

      - name: Package
        if: github.event_name == 'push'
        run: |
          cd app
          CI=false npm run package-linux
          CI=false npm run package-mac
          CI=false npm run package-win
          cd release-builds
          zip -r -y App-linux-x64.zip App-linux-x64
          zip -r -y App-darwin-x64.zip App-darwin-x64
          zip -r -y App-win32-x64.zip App-win32-x64

      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}/${{ github.sha }}
          draft: true
          files: |
            app/release-builds/App-linux-x64.zip
            app/release-builds/App-darwin-x64.zip
            app/release-builds/App-win32-x64.zip

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: app/build
